### ISSUE TITLE
Permission denied when verifying Primo output

### ISSUE THREAD

**Issue by mirabilos** [tomato42/ecpp-verifier#47]
I’ve run Primo as separate user account, but the output files are readable. However:

```
tglase@tglase:/opt/primo/ecpp-verifier $ parallel -j5 -i sh -c "echo {} && python3 
in/primo-B42E8004547B2-001.out
in/primo-B42E8004547B2-005.out
in/primo-B42E8004547B2-002.out
in/primo-B42E8004547B2-004.out
in/primo-B42E8004547B2-003.out
Traceback (most recent call last):
  File "/opt/primo/ecpp-verifier/ecpp", line 404, in <module>
    main()
  File "/opt/primo/ecpp-verifier/ecpp", line 377, in main
    cert = read_config(input_file, False)
  File "/opt/primo/ecpp-verifier/ecpp", line 68, in read_config
    with open(filename, "r+") as fp:
PermissionError: [Errno 13] Permission denied: 'in/primo-B42E8004547B2-001.out'
[…]
```

The file *is* readable though:

```
tglase@tglase:/opt/primo/ecpp-verifier $ ll in/primo-B42E8004547B2-001.out
-rw-r--r-- 1 primo primo 29288 22. Aug 01:16 in/primo-B42E8004547B2-001.out
tglase@tglase:/opt/primo/ecpp-verifier $ head -1 in/primo-B42E8004547B2-001.out
[PRIMO - Primality Certificate]
```

**Comment by tomato42** [comment]
hmm, not sure why it's using `open()` with flag for updating, may be needed for python2 compatibility for handling `bytes`
